// <auto-generated />
using System;
using AccessOneMonitor.Data.Configuration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AccessOneMonitor.Data.Migrations
{
    [DbContext(typeof(DbContextConfiguration))]
    [Migration("20191012152023_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AccessOneMonitor.Data.Entities.Computer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("FreeSpace");

                    b.Property<string>("HostName");

                    b.Property<string>("Ip");

                    b.HasKey("Id");

                    b.ToTable("dbo.Computers");
                });

            modelBuilder.Entity("AccessOneMonitor.Data.Entities.Execution", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("ComputerId");

                    b.Property<long>("ProcessId");

                    b.HasKey("Id");

                    b.HasIndex("ComputerId");

                    b.HasIndex("ProcessId");

                    b.ToTable("dbo.Executions");
                });

            modelBuilder.Entity("AccessOneMonitor.Data.Entities.Process", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("ComputerId");

                    b.Property<string>("Description");

                    b.Property<string>("MemoryAllocation");

                    b.Property<string>("Name");

                    b.Property<string>("Path");

                    b.Property<string>("Version");

                    b.HasKey("Id");

                    b.HasIndex("ComputerId");

                    b.ToTable("dbo.Processes");
                });

            modelBuilder.Entity("AccessOneMonitor.Data.Entities.Execution", b =>
                {
                    b.HasOne("AccessOneMonitor.Data.Entities.Computer", "Computer")
                        .WithMany()
                        .HasForeignKey("ComputerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AccessOneMonitor.Data.Entities.Process", "Process")
                        .WithMany()
                        .HasForeignKey("ProcessId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AccessOneMonitor.Data.Entities.Process", b =>
                {
                    b.HasOne("AccessOneMonitor.Data.Entities.Computer")
                        .WithMany("Processes")
                        .HasForeignKey("ComputerId");
                });
#pragma warning restore 612, 618
        }
    }
}
