// <auto-generated />
using System;
using AccessOneMonitor.Data.Configuration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AccessOneMonitor.Data.Migrations
{
    [DbContext(typeof(DbContextConfiguration))]
    [Migration("20191012171817_AlterColumnTables")]
    partial class AlterColumnTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AccessOneMonitor.Data.Entities.Command", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<int>("Type");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.ToTable("dbo.Commands");
                });

            modelBuilder.Entity("AccessOneMonitor.Data.Entities.Computer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("FreeSpace");

                    b.Property<string>("HostName");

                    b.Property<string>("Ip");

                    b.HasKey("Id");

                    b.ToTable("dbo.Computers");
                });

            modelBuilder.Entity("AccessOneMonitor.Data.Entities.Execution", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CommandId");

                    b.Property<long>("ComputerId");

                    b.Property<DateTime?>("DateExecution");

                    b.Property<string>("Output");

                    b.Property<int>("Status");

                    b.HasKey("Id");

                    b.HasIndex("CommandId");

                    b.HasIndex("ComputerId");

                    b.ToTable("dbo.Executions");
                });

            modelBuilder.Entity("AccessOneMonitor.Data.Entities.Execution", b =>
                {
                    b.HasOne("AccessOneMonitor.Data.Entities.Command", "Command")
                        .WithMany("Executions")
                        .HasForeignKey("CommandId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AccessOneMonitor.Data.Entities.Computer", "Computer")
                        .WithMany("Executions")
                        .HasForeignKey("ComputerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
